name:                beam-demoblog
version:             0.1.0.0
github:              "githubuser/beam-demoblog"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/beam-demoblog#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- mtl
- lens
- beam-core
- beam-sqlite
- sqlite-simple
- beam-migrate
- beam-postgres
- postgresql-simple


library:
  source-dirs: src
  default-extensions: 
  - DeriveGeneric 
  - GADTs 
  - OverloadedStrings 
  - FlexibleContexts 
  - FlexibleInstances
  - TypeFamilies
  - TypeApplications

executables:
  beam-demoblog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beam-demoblog

tests:
  beam-demoblog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beam-demoblog
